node {
   def commit_id
   stage('Preparation') {
     checkout scm
     sh "git rev-parse --short HEAD > .git/commit-id"                        
     commit_id = readFile('.git/commit-id').trim()
   }
   stage('test') {
     nodejs(nodeJSInstallationName: 'nodejs') {
       sh 'npm install --only=dev'
       sh 'npm audit fix --force'
       sh 'npm test'
     }
   }
   stage('docker build/push') {
   
   // Create a temporary docker config directory
   withEnv(["DOCKER_CONFIG=" + pwd(tmp:true) + "/.docker"]) {

     // Create a temporary Docker config file
     sh '''
       mkdir -p \${DOCKER_CONFIG}
       echo '{"credsStore":"envvars"}' > \${DOCKER_CONFIG}/config.json
     '''
     withCredentials([usernamePassword(credentialsId: 'dockerhub', passwordVariable: 'DOCKER_CREDS_PASSWORD', usernameVariable: 'DOCKER_CREDS_USERNAME')]) {

           // Run docker commands ....
       def app = docker.build("alinbratosin/docker-nodejs-demo:${commit_id}", '.').push()
     }
   }
}
}
